services:
  workout-server:
    build:
      context: .
      dockerfile: ./build/workout/Dockerfile
    container_name: workout-server
    restart: always
    environment:
      - ENV=${ENV}
      - PORT=${SERVER_CONTAINER_PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_CONTAINER_PORT}
      - DB_SSL_MODE=${DB_SSL_MODE}
      - AUTH_SERVICE_HOST=${AUTH_SERVICE_HOST}
      - AUTH_SERVICE_PORT=${AUTH_SERVICE_PORT}
    depends_on:
      workout-db:
        condition: service_healthy
    ports:
      - "${SERVER_HOST_PORT}:${SERVER_CONTAINER_PORT}"

  workout-grpc-gateway:
    build:
      context: .
      dockerfile: ./build/gateway/Dockerfile
    container_name: workout-grpc-gateway
    restart: always
    environment:
      - ENV=${ENV}
      - PORT=${GRPC_GATEWAY_CONTAINER_PORT}
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_CONTAINER_PORT}
    ports:
      - "${GRPC_GATEWAY_HOST_PORT}:${GRPC_GATEWAY_CONTAINER_PORT}"

  workout-db:
    image: postgres:17
    container_name: workout-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_HOST_PORT}:${DB_CONTAINER_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - workout-db-data:/var/lib/postgresql/data

volumes:
  workout-db-data: