// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/workout/workout.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/workout/workout.go -destination=mocks/domain/workout/mock_workout.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	user "github.com/qkitzero/workout-service/internal/domain/user"
	workout "github.com/qkitzero/workout-service/internal/domain/workout"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkout is a mock of Workout interface.
type MockWorkout struct {
	ctrl     *gomock.Controller
	recorder *MockWorkoutMockRecorder
	isgomock struct{}
}

// MockWorkoutMockRecorder is the mock recorder for MockWorkout.
type MockWorkoutMockRecorder struct {
	mock *MockWorkout
}

// NewMockWorkout creates a new mock instance.
func NewMockWorkout(ctrl *gomock.Controller) *MockWorkout {
	mock := &MockWorkout{ctrl: ctrl}
	mock.recorder = &MockWorkoutMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkout) EXPECT() *MockWorkoutMockRecorder {
	return m.recorder
}

// CreatedAt mocks base method.
func (m *MockWorkout) CreatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// CreatedAt indicates an expected call of CreatedAt.
func (mr *MockWorkoutMockRecorder) CreatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatedAt", reflect.TypeOf((*MockWorkout)(nil).CreatedAt))
}

// FinishedAt mocks base method.
func (m *MockWorkout) FinishedAt() *time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishedAt")
	ret0, _ := ret[0].(*time.Time)
	return ret0
}

// FinishedAt indicates an expected call of FinishedAt.
func (mr *MockWorkoutMockRecorder) FinishedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishedAt", reflect.TypeOf((*MockWorkout)(nil).FinishedAt))
}

// ID mocks base method.
func (m *MockWorkout) ID() workout.WorkoutID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(workout.WorkoutID)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockWorkoutMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockWorkout)(nil).ID))
}

// IsFinished mocks base method.
func (m *MockWorkout) IsFinished() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFinished")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsFinished indicates an expected call of IsFinished.
func (mr *MockWorkoutMockRecorder) IsFinished() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFinished", reflect.TypeOf((*MockWorkout)(nil).IsFinished))
}

// StartedAt mocks base method.
func (m *MockWorkout) StartedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// StartedAt indicates an expected call of StartedAt.
func (mr *MockWorkoutMockRecorder) StartedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartedAt", reflect.TypeOf((*MockWorkout)(nil).StartedAt))
}

// UserID mocks base method.
func (m *MockWorkout) UserID() user.UserID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserID")
	ret0, _ := ret[0].(user.UserID)
	return ret0
}

// UserID indicates an expected call of UserID.
func (mr *MockWorkoutMockRecorder) UserID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserID", reflect.TypeOf((*MockWorkout)(nil).UserID))
}
