// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/workout/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/workout/repository.go -destination=mocks/domain/workout/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	user "github.com/qkitzero/workout-service/internal/domain/user"
	workout "github.com/qkitzero/workout-service/internal/domain/workout"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkoutRepository is a mock of WorkoutRepository interface.
type MockWorkoutRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWorkoutRepositoryMockRecorder
	isgomock struct{}
}

// MockWorkoutRepositoryMockRecorder is the mock recorder for MockWorkoutRepository.
type MockWorkoutRepositoryMockRecorder struct {
	mock *MockWorkoutRepository
}

// NewMockWorkoutRepository creates a new mock instance.
func NewMockWorkoutRepository(ctrl *gomock.Controller) *MockWorkoutRepository {
	mock := &MockWorkoutRepository{ctrl: ctrl}
	mock.recorder = &MockWorkoutRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkoutRepository) EXPECT() *MockWorkoutRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWorkoutRepository) Create(ctx context.Context, w workout.Workout) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, w)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWorkoutRepositoryMockRecorder) Create(ctx, w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWorkoutRepository)(nil).Create), ctx, w)
}

// Exists mocks base method.
func (m *MockWorkoutRepository) Exists(ctx context.Context, id workout.WorkoutID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockWorkoutRepositoryMockRecorder) Exists(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockWorkoutRepository)(nil).Exists), ctx, id)
}

// FindByID mocks base method.
func (m *MockWorkoutRepository) FindByID(ctx context.Context, id workout.WorkoutID) (workout.Workout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(workout.Workout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockWorkoutRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockWorkoutRepository)(nil).FindByID), ctx, id)
}

// FindByUserID mocks base method.
func (m *MockWorkoutRepository) FindByUserID(ctx context.Context, userID user.UserID, from, to *time.Time) ([]workout.Workout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID, from, to)
	ret0, _ := ret[0].([]workout.Workout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockWorkoutRepositoryMockRecorder) FindByUserID(ctx, userID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockWorkoutRepository)(nil).FindByUserID), ctx, userID, from, to)
}

// Update mocks base method.
func (m *MockWorkoutRepository) Update(ctx context.Context, w workout.Workout) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, w)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockWorkoutRepositoryMockRecorder) Update(ctx, w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWorkoutRepository)(nil).Update), ctx, w)
}
