// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/muscle/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/muscle/repository.go -destination=mocks/domain/muscle/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	i18n "github.com/qkitzero/workout-service/internal/domain/i18n"
	muscle "github.com/qkitzero/workout-service/internal/domain/muscle"
	gomock "go.uber.org/mock/gomock"
)

// MockMuscleRepository is a mock of MuscleRepository interface.
type MockMuscleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMuscleRepositoryMockRecorder
	isgomock struct{}
}

// MockMuscleRepositoryMockRecorder is the mock recorder for MockMuscleRepository.
type MockMuscleRepositoryMockRecorder struct {
	mock *MockMuscleRepository
}

// NewMockMuscleRepository creates a new mock instance.
func NewMockMuscleRepository(ctrl *gomock.Controller) *MockMuscleRepository {
	mock := &MockMuscleRepository{ctrl: ctrl}
	mock.recorder = &MockMuscleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMuscleRepository) EXPECT() *MockMuscleRepositoryMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockMuscleRepository) FindAll(ctx context.Context, lang i18n.Language) ([]muscle.Muscle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, lang)
	ret0, _ := ret[0].([]muscle.Muscle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockMuscleRepositoryMockRecorder) FindAll(ctx, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockMuscleRepository)(nil).FindAll), ctx, lang)
}
