// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/muscle/muscle.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/muscle/muscle.go -destination=mocks/domain/muscle/mock_muscle.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	muscle "github.com/qkitzero/workout-service/internal/domain/muscle"
	gomock "go.uber.org/mock/gomock"
)

// MockMuscle is a mock of Muscle interface.
type MockMuscle struct {
	ctrl     *gomock.Controller
	recorder *MockMuscleMockRecorder
	isgomock struct{}
}

// MockMuscleMockRecorder is the mock recorder for MockMuscle.
type MockMuscleMockRecorder struct {
	mock *MockMuscle
}

// NewMockMuscle creates a new mock instance.
func NewMockMuscle(ctrl *gomock.Controller) *MockMuscle {
	mock := &MockMuscle{ctrl: ctrl}
	mock.recorder = &MockMuscleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMuscle) EXPECT() *MockMuscleMockRecorder {
	return m.recorder
}

// Code mocks base method.
func (m *MockMuscle) Code() muscle.Code {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Code")
	ret0, _ := ret[0].(muscle.Code)
	return ret0
}

// Code indicates an expected call of Code.
func (mr *MockMuscleMockRecorder) Code() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Code", reflect.TypeOf((*MockMuscle)(nil).Code))
}

// ID mocks base method.
func (m *MockMuscle) ID() muscle.MuscleID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(muscle.MuscleID)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockMuscleMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockMuscle)(nil).ID))
}

// Name mocks base method.
func (m *MockMuscle) Name() muscle.Name {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(muscle.Name)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockMuscleMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockMuscle)(nil).Name))
}
