// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/muscle/usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/application/muscle/usecase.go -destination=mocks/application/muscle/mock_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	muscle "github.com/qkitzero/workout-service/internal/domain/muscle"
	gomock "go.uber.org/mock/gomock"
)

// MockMuscleUsecase is a mock of MuscleUsecase interface.
type MockMuscleUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockMuscleUsecaseMockRecorder
	isgomock struct{}
}

// MockMuscleUsecaseMockRecorder is the mock recorder for MockMuscleUsecase.
type MockMuscleUsecaseMockRecorder struct {
	mock *MockMuscleUsecase
}

// NewMockMuscleUsecase creates a new mock instance.
func NewMockMuscleUsecase(ctrl *gomock.Controller) *MockMuscleUsecase {
	mock := &MockMuscleUsecase{ctrl: ctrl}
	mock.recorder = &MockMuscleUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMuscleUsecase) EXPECT() *MockMuscleUsecaseMockRecorder {
	return m.recorder
}

// ListMuscles mocks base method.
func (m *MockMuscleUsecase) ListMuscles(ctx context.Context, lang string) ([]muscle.Muscle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMuscles", ctx, lang)
	ret0, _ := ret[0].([]muscle.Muscle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMuscles indicates an expected call of ListMuscles.
func (mr *MockMuscleUsecaseMockRecorder) ListMuscles(ctx, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMuscles", reflect.TypeOf((*MockMuscleUsecase)(nil).ListMuscles), ctx, lang)
}
