// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/set/set.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/set/set.go -destination=mocks/domain/set/mock_set.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	exercise "github.com/qkitzero/workout-service/internal/domain/exercise"
	set "github.com/qkitzero/workout-service/internal/domain/set"
	user "github.com/qkitzero/workout-service/internal/domain/user"
	gomock "go.uber.org/mock/gomock"
)

// MockSet is a mock of Set interface.
type MockSet struct {
	ctrl     *gomock.Controller
	recorder *MockSetMockRecorder
	isgomock struct{}
}

// MockSetMockRecorder is the mock recorder for MockSet.
type MockSetMockRecorder struct {
	mock *MockSet
}

// NewMockSet creates a new mock instance.
func NewMockSet(ctrl *gomock.Controller) *MockSet {
	mock := &MockSet{ctrl: ctrl}
	mock.recorder = &MockSetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSet) EXPECT() *MockSetMockRecorder {
	return m.recorder
}

// CreatedAt mocks base method.
func (m *MockSet) CreatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// CreatedAt indicates an expected call of CreatedAt.
func (mr *MockSetMockRecorder) CreatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatedAt", reflect.TypeOf((*MockSet)(nil).CreatedAt))
}

// ExerciseID mocks base method.
func (m *MockSet) ExerciseID() exercise.ExerciseID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExerciseID")
	ret0, _ := ret[0].(exercise.ExerciseID)
	return ret0
}

// ExerciseID indicates an expected call of ExerciseID.
func (mr *MockSetMockRecorder) ExerciseID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExerciseID", reflect.TypeOf((*MockSet)(nil).ExerciseID))
}

// ID mocks base method.
func (m *MockSet) ID() set.SetID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(set.SetID)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockSetMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockSet)(nil).ID))
}

// Rep mocks base method.
func (m *MockSet) Rep() set.Rep {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rep")
	ret0, _ := ret[0].(set.Rep)
	return ret0
}

// Rep indicates an expected call of Rep.
func (mr *MockSetMockRecorder) Rep() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rep", reflect.TypeOf((*MockSet)(nil).Rep))
}

// TrainedAt mocks base method.
func (m *MockSet) TrainedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrainedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// TrainedAt indicates an expected call of TrainedAt.
func (mr *MockSetMockRecorder) TrainedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrainedAt", reflect.TypeOf((*MockSet)(nil).TrainedAt))
}

// UserID mocks base method.
func (m *MockSet) UserID() user.UserID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserID")
	ret0, _ := ret[0].(user.UserID)
	return ret0
}

// UserID indicates an expected call of UserID.
func (mr *MockSetMockRecorder) UserID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserID", reflect.TypeOf((*MockSet)(nil).UserID))
}

// Weight mocks base method.
func (m *MockSet) Weight() set.Weight {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Weight")
	ret0, _ := ret[0].(set.Weight)
	return ret0
}

// Weight indicates an expected call of Weight.
func (mr *MockSetMockRecorder) Weight() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Weight", reflect.TypeOf((*MockSet)(nil).Weight))
}
