// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/set/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/set/repository.go -destination=mocks/domain/set/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	set "github.com/qkitzero/workout-service/internal/domain/set"
	user "github.com/qkitzero/workout-service/internal/domain/user"
	workout "github.com/qkitzero/workout-service/internal/domain/workout"
	gomock "go.uber.org/mock/gomock"
)

// MockSetRepository is a mock of SetRepository interface.
type MockSetRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSetRepositoryMockRecorder
	isgomock struct{}
}

// MockSetRepositoryMockRecorder is the mock recorder for MockSetRepository.
type MockSetRepositoryMockRecorder struct {
	mock *MockSetRepository
}

// NewMockSetRepository creates a new mock instance.
func NewMockSetRepository(ctrl *gomock.Controller) *MockSetRepository {
	mock := &MockSetRepository{ctrl: ctrl}
	mock.recorder = &MockSetRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSetRepository) EXPECT() *MockSetRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSetRepository) Create(ctx context.Context, arg1 set.Set) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSetRepositoryMockRecorder) Create(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSetRepository)(nil).Create), ctx, arg1)
}

// FindByUserID mocks base method.
func (m *MockSetRepository) FindByUserID(ctx context.Context, userID user.UserID) ([]set.Set, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID)
	ret0, _ := ret[0].([]set.Set)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockSetRepositoryMockRecorder) FindByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockSetRepository)(nil).FindByUserID), ctx, userID)
}

// FindByWorkoutID mocks base method.
func (m *MockSetRepository) FindByWorkoutID(ctx context.Context, workoutID workout.WorkoutID) ([]set.Set, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByWorkoutID", ctx, workoutID)
	ret0, _ := ret[0].([]set.Set)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByWorkoutID indicates an expected call of FindByWorkoutID.
func (mr *MockSetRepositoryMockRecorder) FindByWorkoutID(ctx, workoutID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByWorkoutID", reflect.TypeOf((*MockSetRepository)(nil).FindByWorkoutID), ctx, workoutID)
}
