// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/exercise/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/exercise/repository.go -destination=mocks/domain/exercise/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	exercise "github.com/qkitzero/workout-service/internal/domain/exercise"
	gomock "go.uber.org/mock/gomock"
)

// MockExerciseRepository is a mock of ExerciseRepository interface.
type MockExerciseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockExerciseRepositoryMockRecorder
	isgomock struct{}
}

// MockExerciseRepositoryMockRecorder is the mock recorder for MockExerciseRepository.
type MockExerciseRepositoryMockRecorder struct {
	mock *MockExerciseRepository
}

// NewMockExerciseRepository creates a new mock instance.
func NewMockExerciseRepository(ctrl *gomock.Controller) *MockExerciseRepository {
	mock := &MockExerciseRepository{ctrl: ctrl}
	mock.recorder = &MockExerciseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExerciseRepository) EXPECT() *MockExerciseRepositoryMockRecorder {
	return m.recorder
}

// Exists mocks base method.
func (m *MockExerciseRepository) Exists(id exercise.ExerciseID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockExerciseRepositoryMockRecorder) Exists(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockExerciseRepository)(nil).Exists), id)
}

// FindAll mocks base method.
func (m *MockExerciseRepository) FindAll() ([]exercise.Exercise, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]exercise.Exercise)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockExerciseRepositoryMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockExerciseRepository)(nil).FindAll))
}

// FindByID mocks base method.
func (m *MockExerciseRepository) FindByID(id exercise.ExerciseID) (exercise.Exercise, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(exercise.Exercise)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockExerciseRepositoryMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockExerciseRepository)(nil).FindByID), id)
}
