// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/exercise/exercise.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/exercise/exercise.go -destination=mocks/domain/exercise/mock_exercise.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	exercise "github.com/qkitzero/workout-service/internal/domain/exercise"
	gomock "go.uber.org/mock/gomock"
)

// MockExercise is a mock of Exercise interface.
type MockExercise struct {
	ctrl     *gomock.Controller
	recorder *MockExerciseMockRecorder
	isgomock struct{}
}

// MockExerciseMockRecorder is the mock recorder for MockExercise.
type MockExerciseMockRecorder struct {
	mock *MockExercise
}

// NewMockExercise creates a new mock instance.
func NewMockExercise(ctrl *gomock.Controller) *MockExercise {
	mock := &MockExercise{ctrl: ctrl}
	mock.recorder = &MockExerciseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExercise) EXPECT() *MockExerciseMockRecorder {
	return m.recorder
}

// Category mocks base method.
func (m *MockExercise) Category() exercise.Category {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Category")
	ret0, _ := ret[0].(exercise.Category)
	return ret0
}

// Category indicates an expected call of Category.
func (mr *MockExerciseMockRecorder) Category() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Category", reflect.TypeOf((*MockExercise)(nil).Category))
}

// Code mocks base method.
func (m *MockExercise) Code() exercise.Code {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Code")
	ret0, _ := ret[0].(exercise.Code)
	return ret0
}

// Code indicates an expected call of Code.
func (mr *MockExerciseMockRecorder) Code() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Code", reflect.TypeOf((*MockExercise)(nil).Code))
}

// ID mocks base method.
func (m *MockExercise) ID() exercise.ExerciseID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(exercise.ExerciseID)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockExerciseMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockExercise)(nil).ID))
}

// Name mocks base method.
func (m *MockExercise) Name(lang exercise.Language) exercise.Name {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name", lang)
	ret0, _ := ret[0].(exercise.Name)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockExerciseMockRecorder) Name(lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockExercise)(nil).Name), lang)
}

// Translations mocks base method.
func (m *MockExercise) Translations() []exercise.Translation {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Translations")
	ret0, _ := ret[0].([]exercise.Translation)
	return ret0
}

// Translations indicates an expected call of Translations.
func (mr *MockExerciseMockRecorder) Translations() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Translations", reflect.TypeOf((*MockExercise)(nil).Translations))
}
