// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/set/usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/application/set/usecase.go -destination=mocks/application/set/mock_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	set "github.com/qkitzero/workout-service/internal/domain/set"
	gomock "go.uber.org/mock/gomock"
)

// MockSetUsecase is a mock of SetUsecase interface.
type MockSetUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockSetUsecaseMockRecorder
	isgomock struct{}
}

// MockSetUsecaseMockRecorder is the mock recorder for MockSetUsecase.
type MockSetUsecaseMockRecorder struct {
	mock *MockSetUsecase
}

// NewMockSetUsecase creates a new mock instance.
func NewMockSetUsecase(ctrl *gomock.Controller) *MockSetUsecase {
	mock := &MockSetUsecase{ctrl: ctrl}
	mock.recorder = &MockSetUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSetUsecase) EXPECT() *MockSetUsecaseMockRecorder {
	return m.recorder
}

// CreateSet mocks base method.
func (m *MockSetUsecase) CreateSet(ctx context.Context, exercise string, rep int32, weight float64, trainedAt time.Time) (set.Set, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSet", ctx, exercise, rep, weight, trainedAt)
	ret0, _ := ret[0].(set.Set)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSet indicates an expected call of CreateSet.
func (mr *MockSetUsecaseMockRecorder) CreateSet(ctx, exercise, rep, weight, trainedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSet", reflect.TypeOf((*MockSetUsecase)(nil).CreateSet), ctx, exercise, rep, weight, trainedAt)
}

// ListSets mocks base method.
func (m *MockSetUsecase) ListSets(ctx context.Context) ([]set.Set, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSets", ctx)
	ret0, _ := ret[0].([]set.Set)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSets indicates an expected call of ListSets.
func (mr *MockSetUsecaseMockRecorder) ListSets(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSets", reflect.TypeOf((*MockSetUsecase)(nil).ListSets), ctx)
}
