// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/workout/usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/application/workout/usecase.go -destination=mocks/application/workout/mock_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	set "github.com/qkitzero/workout-service/internal/domain/set"
	workout "github.com/qkitzero/workout-service/internal/domain/workout"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkoutUsecase is a mock of WorkoutUsecase interface.
type MockWorkoutUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockWorkoutUsecaseMockRecorder
	isgomock struct{}
}

// MockWorkoutUsecaseMockRecorder is the mock recorder for MockWorkoutUsecase.
type MockWorkoutUsecaseMockRecorder struct {
	mock *MockWorkoutUsecase
}

// NewMockWorkoutUsecase creates a new mock instance.
func NewMockWorkoutUsecase(ctrl *gomock.Controller) *MockWorkoutUsecase {
	mock := &MockWorkoutUsecase{ctrl: ctrl}
	mock.recorder = &MockWorkoutUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkoutUsecase) EXPECT() *MockWorkoutUsecaseMockRecorder {
	return m.recorder
}

// FinishWorkout mocks base method.
func (m *MockWorkoutUsecase) FinishWorkout(ctx context.Context, id workout.WorkoutID) (workout.Workout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishWorkout", ctx, id)
	ret0, _ := ret[0].(workout.Workout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinishWorkout indicates an expected call of FinishWorkout.
func (mr *MockWorkoutUsecaseMockRecorder) FinishWorkout(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishWorkout", reflect.TypeOf((*MockWorkoutUsecase)(nil).FinishWorkout), ctx, id)
}

// GetWorkout mocks base method.
func (m *MockWorkoutUsecase) GetWorkout(ctx context.Context, id workout.WorkoutID) (workout.Workout, []set.Set, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkout", ctx, id)
	ret0, _ := ret[0].(workout.Workout)
	ret1, _ := ret[1].([]set.Set)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetWorkout indicates an expected call of GetWorkout.
func (mr *MockWorkoutUsecaseMockRecorder) GetWorkout(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkout", reflect.TypeOf((*MockWorkoutUsecase)(nil).GetWorkout), ctx, id)
}

// ListWorkouts mocks base method.
func (m *MockWorkoutUsecase) ListWorkouts(ctx context.Context, from, to *time.Time) ([]workout.Workout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWorkouts", ctx, from, to)
	ret0, _ := ret[0].([]workout.Workout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWorkouts indicates an expected call of ListWorkouts.
func (mr *MockWorkoutUsecaseMockRecorder) ListWorkouts(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWorkouts", reflect.TypeOf((*MockWorkoutUsecase)(nil).ListWorkouts), ctx, from, to)
}

// StartWorkout mocks base method.
func (m *MockWorkoutUsecase) StartWorkout(ctx context.Context) (workout.Workout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartWorkout", ctx)
	ret0, _ := ret[0].(workout.Workout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartWorkout indicates an expected call of StartWorkout.
func (mr *MockWorkoutUsecaseMockRecorder) StartWorkout(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartWorkout", reflect.TypeOf((*MockWorkoutUsecase)(nil).StartWorkout), ctx)
}
