// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/exercise/usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/application/exercise/usecase.go -destination=mocks/application/exercise/mock_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	exercise "github.com/qkitzero/workout-service/internal/application/exercise"
	gomock "go.uber.org/mock/gomock"
)

// MockExerciseUsecase is a mock of ExerciseUsecase interface.
type MockExerciseUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockExerciseUsecaseMockRecorder
	isgomock struct{}
}

// MockExerciseUsecaseMockRecorder is the mock recorder for MockExerciseUsecase.
type MockExerciseUsecaseMockRecorder struct {
	mock *MockExerciseUsecase
}

// NewMockExerciseUsecase creates a new mock instance.
func NewMockExerciseUsecase(ctrl *gomock.Controller) *MockExerciseUsecase {
	mock := &MockExerciseUsecase{ctrl: ctrl}
	mock.recorder = &MockExerciseUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExerciseUsecase) EXPECT() *MockExerciseUsecaseMockRecorder {
	return m.recorder
}

// ListExercises mocks base method.
func (m *MockExerciseUsecase) ListExercises(ctx context.Context, lang string) ([]exercise.ListedExercise, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExercises", ctx, lang)
	ret0, _ := ret[0].([]exercise.ListedExercise)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExercises indicates an expected call of ListExercises.
func (mr *MockExerciseUsecaseMockRecorder) ListExercises(ctx, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExercises", reflect.TypeOf((*MockExerciseUsecase)(nil).ListExercises), ctx, lang)
}
